"""add Showcase, Tour, TourSearch, TourError

Revision ID: 8a7554bb9c55
Revises: 5f249aacdb61
Create Date: 2021-06-01 14:34:04.764501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a7554bb9c55'
down_revision = '5f249aacdb61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('showcase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('order_index', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tour',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('showcase_id', sa.Integer(), nullable=True),
    sa.Column('order_index', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('destination', sa.String(length=255), nullable=True),
    sa.Column('date_start', sa.Date(), nullable=True),
    sa.Column('date_stop', sa.Date(), nullable=True),
    sa.Column('from_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('transport_id', sa.Integer(), nullable=True),
    sa.Column('food_id', sa.Integer(), nullable=True),
    sa.Column('length_id', sa.Integer(), nullable=True),
    sa.Column('link', sa.String(length=255), nullable=True),
    sa.Column('errors', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('errors_update', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['tour_category.id'], ),
    sa.ForeignKeyConstraint(['food_id'], ['tour_food.id'], ),
    sa.ForeignKeyConstraint(['from_id'], ['tour_from.id'], ),
    sa.ForeignKeyConstraint(['length_id'], ['tour_length.id'], ),
    sa.ForeignKeyConstraint(['showcase_id'], ['showcase.id'], ),
    sa.ForeignKeyConstraint(['transport_id'], ['tour_transport.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tour_error',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('showcase_id', sa.Integer(), nullable=False),
    sa.Column('tour_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('update', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('errors', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['showcase_id'], ['showcase.id'], ),
    sa.ForeignKeyConstraint(['tour_id'], ['tour.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tour_search',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tour_id', sa.Integer(), nullable=False),
    sa.Column('lang', sa.Integer(), nullable=False),
    sa.Column('src_json', sa.Text(), nullable=False),
    sa.Column('tour_api_id', sa.String(length=255), nullable=False),
    sa.Column('update', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('hotelId', sa.Integer(), nullable=False),
    sa.Column('imgSrc', sa.String(length=255), nullable=False),
    sa.Column('hotelName', sa.String(length=255), nullable=False),
    sa.Column('fullHotelName', sa.String(length=255), nullable=False),
    sa.Column('hotelStars', sa.String(length=255), nullable=False),
    sa.Column('countryId', sa.Integer(), nullable=False),
    sa.Column('countryName', sa.String(length=255), nullable=False),
    sa.Column('cityId', sa.Integer(), nullable=False),
    sa.Column('cityName', sa.String(length=255), nullable=False),
    sa.Column('resortName', sa.String(length=255), nullable=False),
    sa.Column('dateString', sa.Date(), nullable=False),
    sa.Column('cityFromId', sa.Integer(), nullable=False),
    sa.Column('cityFrom', sa.String(length=255), nullable=False),
    sa.Column('locationFromString', sa.String(length=255), nullable=False),
    sa.Column('foodString', sa.String(length=255), nullable=False),
    sa.Column('dateDurationString', sa.String(length=255), nullable=False),
    sa.Column('operatorId', sa.Integer(), nullable=False),
    sa.Column('operatorName', sa.String(length=255), nullable=False),
    sa.Column('promo', sa.Boolean(), nullable=False),
    sa.Column('price', sa.String(length=255), nullable=False),
    sa.Column('currency', sa.String(length=255), nullable=False),
    sa.Column('priceUsd', sa.String(length=255), nullable=True),
    sa.Column('priceEuro', sa.String(length=255), nullable=True),
    sa.Column('priceUah', sa.String(length=255), nullable=False),
    sa.Column('priceUahOne', sa.String(length=255), nullable=False),
    sa.Column('tourLink', sa.String(length=255), nullable=False),
    sa.Column('transport', sa.String(length=255), nullable=False),
    sa.Column('food', sa.String(length=255), nullable=False),
    sa.Column('length', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lang'], ['lang.id'], ),
    sa.ForeignKeyConstraint(['tour_id'], ['tour.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tour_id', 'lang', name='_tour_id_lang_uc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tour_search')
    op.drop_table('tour_error')
    op.drop_table('tour')
    op.drop_table('showcase')
    # ### end Alembic commands ###
