"""add column otpusk_hotel_ta.name and otpusk_hotel_ta_cache.name

Revision ID: 540d46123add
Revises: 6fa997fc5d97
Create Date: 2021-10-01 14:29:03.615692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '540d46123add'
down_revision = '6fa997fc5d97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('otpusk_hotel_ta', sa.Column('name', sa.String(length=255), nullable=True))
    op.add_column('otpusk_hotel_ta_cache', sa.Column('name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('otpusk_hotel_ta_cache', 'name')
    op.drop_column('otpusk_hotel_ta', 'name')
    # ### end Alembic commands ###
