"""add otpusk_hotel_ta.expired

Revision ID: defc1e11bc14
Revises: e2badc912e31
Create Date: 2021-09-30 18:02:33.611662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'defc1e11bc14'
down_revision = 'e2badc912e31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('otpusk_hotel_ta', sa.Column('expired', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('otpusk_hotel_ta', 'expired')
    # ### end Alembic commands ###
