"""add fields tour.manual_update_date and tour.manual_update_pid

Revision ID: 131d790511c3
Revises: d785a2a0a4cb
Create Date: 2021-07-17 14:02:39.364257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '131d790511c3'
down_revision = 'd785a2a0a4cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tour', sa.Column('manual_update_pid', sa.Integer(), nullable=True))
    op.add_column('tour', sa.Column('manual_update_date', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tour', 'manual_update_date')
    op.drop_column('tour', 'manual_update_pid')
    # ### end Alembic commands ###
