"""add table pay

Revision ID: b92cdf2b9036
Revises: 131d790511c3
Create Date: 2021-07-23 17:53:36.968829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b92cdf2b9036'
down_revision = '131d790511c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pay',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('json_data', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pay')
    # ### end Alembic commands ###
