"""add field tour.index

Revision ID: 231938bde80c
Revises: e94aeb6bd7ba
Create Date: 2021-06-23 23:11:50.070531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '231938bde80c'
down_revision = 'e94aeb6bd7ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tour', sa.Column('index', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tour', 'index')
    # ### end Alembic commands ###
