"""add otpusk_cities.update

Revision ID: 8650eb53a45b
Revises: 8a7554bb9c55
Create Date: 2021-06-01 15:31:38.775824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8650eb53a45b'
down_revision = '8a7554bb9c55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('otpusk_cities', sa.Column('update', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('otpusk_cities', 'update')
    # ### end Alembic commands ###
