"""add fileds to tour_search

Revision ID: fde198fefe94
Revises: 26c4ebe48df0
Create Date: 2021-07-04 12:27:31.595383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fde198fefe94'
down_revision = '26c4ebe48df0'
branch_labels = None
depends_on = None

# add to repo
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tour_search', sa.Column('cityPortIata', sa.String(length=255), nullable=True))
    op.add_column('tour_search', sa.Column('cityPortName', sa.String(length=255), nullable=True))
    op.add_column('tour_search', sa.Column('locationLat', sa.Float(), nullable=True))
    op.add_column('tour_search', sa.Column('locationLng', sa.Float(), nullable=True))
    op.add_column('tour_search', sa.Column('locationZoom', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tour_search', 'locationZoom')
    op.drop_column('tour_search', 'locationLng')
    op.drop_column('tour_search', 'locationLat')
    op.drop_column('tour_search', 'cityPortName')
    op.drop_column('tour_search', 'cityPortIata')
    # ### end Alembic commands ###
