"""add fileds tour_search.deptFrom and tour_search.deptTo

Revision ID: d785a2a0a4cb
Revises: fde198fefe94
Create Date: 2021-07-05 11:30:18.083344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd785a2a0a4cb'
down_revision = 'fde198fefe94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tour_search', sa.Column('deptFrom', sa.DateTime(), nullable=True))
    op.add_column('tour_search', sa.Column('deptTo', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tour_search', 'deptTo')
    op.drop_column('tour_search', 'deptFrom')
    # ### end Alembic commands ###
