"""add otpusk.ports

Revision ID: 26c4ebe48df0
Revises: 231938bde80c
Create Date: 2021-06-29 18:35:34.762504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26c4ebe48df0'
down_revision = '231938bde80c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otpusk_ports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('otpusk_id', sa.Integer(), nullable=False),
    sa.Column('lang', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('country', sa.Integer(), nullable=False),
    sa.Column('iata', sa.CHAR(length=3), nullable=False),
    sa.ForeignKeyConstraint(['lang'], ['lang.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('iata', 'lang', name='_otpusk_iata_lang_uc'),
    sa.UniqueConstraint('otpusk_id', 'lang', name='_otpusk_id_lang_uc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('otpusk_ports')
    # ### end Alembic commands ###
