"""add Lang

Revision ID: f765e4aa9a1b
Revises: a5d78ee03a67
Create Date: 2021-06-01 13:22:21.746194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f765e4aa9a1b'
down_revision = 'a5d78ee03a67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lang',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=3), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )

    conn = op.get_bind()
    conn.execute("INSERT INTO lang (id, name) VALUES (0, 'rus')")
    conn.execute("INSERT INTO lang (id, name) VALUES (1, 'ukr')")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lang')
    # ### end Alembic commands ###
