"""add OtpuskCoutries, OtpuskFromCities, OtpuskCities, OtpuskOperators

Revision ID: 5f249aacdb61
Revises: c5be1599145a
Create Date: 2021-06-01 14:31:19.938592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f249aacdb61'
down_revision = 'c5be1599145a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otpusk_cities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('otpusk_id', sa.Integer(), nullable=False),
    sa.Column('lang', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('country', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lang'], ['lang.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('otpusk_id', 'lang', name='_otpusk_id_lang_uc')
    )
    op.create_table('otpusk_countris',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('otpusk_id', sa.Integer(), nullable=False),
    sa.Column('lang', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['lang'], ['lang.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('otpusk_id', 'lang', name='_otpusk_id_lang_uc')
    )
    op.create_table('otpusk_from_cities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('otpusk_id', sa.Integer(), nullable=False),
    sa.Column('lang', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('rel', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['lang'], ['lang.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('otpusk_id', 'lang', name='_otpusk_id_lang_uc')
    )
    op.create_table('otpusk_operators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('otpusk_id', sa.Integer(), nullable=False),
    sa.Column('lang', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['lang'], ['lang.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('otpusk_id', 'lang', name='_otpusk_id_lang_uc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('otpusk_operators')
    op.drop_table('otpusk_from_cities')
    op.drop_table('otpusk_countris')
    op.drop_table('otpusk_cities')
    # ### end Alembic commands ###
